// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkGVjQ2fJju16Wj36NyVgguK-K_4hj3nA',
    appId: '1:1036268408505:android:e5dbec413845ccd5ce9568',
    messagingSenderId: '1036268408505',
    projectId: 'chatsapp-d343f',
    storageBucket: 'chatsapp-d343f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF-Ecl1I4MqiAcxqRDNUbigbnweVyD9iE',
    appId: '1:1036268408505:ios:b1fb98e7ab2d8363ce9568',
    messagingSenderId: '1036268408505',
    projectId: 'chatsapp-d343f',
    storageBucket: 'chatsapp-d343f.firebasestorage.app',
    iosBundleId: 'com.example.chatsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxq6WlXda-6lbFD2z-TVgEmiCvuFfoytA',
    appId: '1:1036268408505:web:939dc86b17db6392ce9568',
    messagingSenderId: '1036268408505',
    projectId: 'chatsapp-d343f',
    authDomain: 'chatsapp-d343f.firebaseapp.com',
    storageBucket: 'chatsapp-d343f.firebasestorage.app',
  );

}